# Generated by Django 5.2 on 2025-04-16 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="sector_logos/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Startup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("founding_date", models.DateField()),
                ("logo", models.ImageField(upload_to="logos/")),
                (
                    "sectors",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.sector"
                    ),
                ),
            ],
        ),
    ]
