# Generated by Django 5.2 on 2025-05-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_investor_startup_location_startup_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
