# Generated by Django 5.2 on 2025-05-04 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_startup_website'),
    ]

    operations = [
    ]
