# Generated by Django 5.2 on 2025-05-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250504_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='sectors',
            new_name='sector',
        ),
    ]
