# Generated by Django 5.2 on 2025-05-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_sectors_startup_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
