# Generated by Django 5.2 on 2025-05-08 03:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_sectors_startup_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
