# Generated by Django 5.2 on 2025-05-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_startup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
