# Generated by Django 5.2 on 2025-05-08 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_startup_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='slug',
        ),
    ]
