# Generated by Django 5.2 on 2025-05-16 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customapikey'),
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeyMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('revoked', models.BooleanField(default=False)),
                ('api_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest_framework_api_key.apikey')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomAPIKey',
        ),
    ]
