# Generated by Django 5.2 on 2025-05-08 00:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_startup_slug_alter_startup_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
