# Generated by Django 5.2 on 2025-05-08 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_startup_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='slug',
        ),
    ]
